var searchData=
[
  ['speech_5fdetection_5fgoogle_5ftest_5fogg_5fsentence1_2epy',['speech_detection_google_test_ogg_sentence1.py',['../speech__detection__google__test__ogg__sentence1_8py.html',1,'']]],
  ['speech_5fdetection_5fgoogle_5ftest_5fogg_5fsentence2_2epy',['speech_detection_google_test_ogg_sentence2.py',['../speech__detection__google__test__ogg__sentence2_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fheadset_5fdeutera_2epy',['speech_detection_sphinx_test_headset_deutera.py',['../speech__detection__sphinx__test__headset__deutera_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fheadset_5fnai_5foxi_2epy',['speech_detection_sphinx_test_headset_nai_oxi.py',['../speech__detection__sphinx__test__headset__nai__oxi_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fheadset_5fsteile_5fmail_2epy',['speech_detection_sphinx_test_headset_steile_mail.py',['../speech__detection__sphinx__test__headset__steile__mail_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fnao_5fwav_5f1_5fch_5femail_5frobot_2epy',['speech_detection_sphinx_test_nao_wav_1_ch_email_robot.py',['../speech__detection__sphinx__test__nao__wav__1__ch__email__robot_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fnao_5fwav_5f1_5fch_5fnai_5foxi_2epy',['speech_detection_sphinx_test_nao_wav_1_ch_nai_oxi.py',['../speech__detection__sphinx__test__nao__wav__1__ch__nai__oxi_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fnao_5fwav_5f1_5fch_5fthelw_5fvoithia_2epy',['speech_detection_sphinx_test_nao_wav_1_ch_thelw_voithia.py',['../speech__detection__sphinx__test__nao__wav__1__ch__thelw__voithia_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fnao_5fwav_5f1_5fch_5fyes_5fno_2epy',['speech_detection_sphinx_test_nao_wav_1_ch_yes_no.py',['../speech__detection__sphinx__test__nao__wav__1__ch__yes__no_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5fdeutera_2epy',['speech_detection_sphinx_test_ogg_deutera.py',['../speech__detection__sphinx__test__ogg__deutera_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5fmonday_2epy',['speech_detection_sphinx_test_ogg_monday.py',['../speech__detection__sphinx__test__ogg__monday_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5fno_2epy',['speech_detection_sphinx_test_ogg_no.py',['../speech__detection__sphinx__test__ogg__no_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5foxi_2epy',['speech_detection_sphinx_test_ogg_oxi.py',['../speech__detection__sphinx__test__ogg__oxi_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5ftriti_2epy',['speech_detection_sphinx_test_ogg_triti.py',['../speech__detection__sphinx__test__ogg__triti_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5ftuesday_2epy',['speech_detection_sphinx_test_ogg_tuesday.py',['../speech__detection__sphinx__test__ogg__tuesday_8py.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5fyes_2epy',['speech_detection_sphinx_test_ogg_yes.py',['../speech__detection__sphinx__test__ogg__yes_8py.html',1,'']]]
];
