var searchData=
[
  ['speech_5fdetection_5fgoogle_5ftest_5fogg_5fsentence1',['speech_detection_google_test_ogg_sentence1',['../namespacespeech__detection__google__test__ogg__sentence1.html',1,'']]],
  ['speech_5fdetection_5fgoogle_5ftest_5fogg_5fsentence2',['speech_detection_google_test_ogg_sentence2',['../namespacespeech__detection__google__test__ogg__sentence2.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fheadset_5fdeutera',['speech_detection_sphinx_test_headset_deutera',['../namespacespeech__detection__sphinx__test__headset__deutera.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fheadset_5fnai_5foxi',['speech_detection_sphinx_test_headset_nai_oxi',['../namespacespeech__detection__sphinx__test__headset__nai__oxi.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fheadset_5fsteile_5fmail',['speech_detection_sphinx_test_headset_steile_mail',['../namespacespeech__detection__sphinx__test__headset__steile__mail.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fnao_5fwav_5f1_5fch_5femail_5frobot',['speech_detection_sphinx_test_nao_wav_1_ch_email_robot',['../namespacespeech__detection__sphinx__test__nao__wav__1__ch__email__robot.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fnao_5fwav_5f1_5fch_5fnai_5foxi',['speech_detection_sphinx_test_nao_wav_1_ch_nai_oxi',['../namespacespeech__detection__sphinx__test__nao__wav__1__ch__nai__oxi.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fnao_5fwav_5f1_5fch_5fthelw_5fvoithia',['speech_detection_sphinx_test_nao_wav_1_ch_thelw_voithia',['../namespacespeech__detection__sphinx__test__nao__wav__1__ch__thelw__voithia.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fnao_5fwav_5f1_5fch_5fyes_5fno',['speech_detection_sphinx_test_nao_wav_1_ch_yes_no',['../namespacespeech__detection__sphinx__test__nao__wav__1__ch__yes__no.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5fdeutera',['speech_detection_sphinx_test_ogg_deutera',['../namespacespeech__detection__sphinx__test__ogg__deutera.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5fmonday',['speech_detection_sphinx_test_ogg_monday',['../namespacespeech__detection__sphinx__test__ogg__monday.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5fno',['speech_detection_sphinx_test_ogg_no',['../namespacespeech__detection__sphinx__test__ogg__no.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5foxi',['speech_detection_sphinx_test_ogg_oxi',['../namespacespeech__detection__sphinx__test__ogg__oxi.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5ftriti',['speech_detection_sphinx_test_ogg_triti',['../namespacespeech__detection__sphinx__test__ogg__triti.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5ftuesday',['speech_detection_sphinx_test_ogg_tuesday',['../namespacespeech__detection__sphinx__test__ogg__tuesday.html',1,'']]],
  ['speech_5fdetection_5fsphinx_5ftest_5fogg_5fyes',['speech_detection_sphinx_test_ogg_yes',['../namespacespeech__detection__sphinx__test__ogg__yes.html',1,'']]]
];
