var hierarchy =
[
    [ "rapp::cloud::asio_handler", "classrapp_1_1cloud_1_1asio__handler.html", [
      [ "rapp::cloud::asio_service_http", "classrapp_1_1cloud_1_1asio__service__http.html", [
        [ "rapp::cloud::available_services", "classrapp_1_1cloud_1_1available__services.html", null ],
        [ "rapp::cloud::cognitive_get_history", "classrapp_1_1cloud_1_1cognitive__get__history.html", null ],
        [ "rapp::cloud::cognitive_get_scores", "classrapp_1_1cloud_1_1cognitive__get__scores.html", null ],
        [ "rapp::cloud::cognitive_record_performance", "classrapp_1_1cloud_1_1cognitive__record__performance.html", null ],
        [ "rapp::cloud::cognitive_test_selector", "classrapp_1_1cloud_1_1cognitive__test__selector.html", null ],
        [ "rapp::cloud::email_fetch", "classrapp_1_1cloud_1_1email__fetch.html", null ],
        [ "rapp::cloud::email_send", "classrapp_1_1cloud_1_1email__send.html", null ],
        [ "rapp::cloud::face_detection", "classrapp_1_1cloud_1_1face__detection.html", null ],
        [ "rapp::cloud::geolocation", "classrapp_1_1cloud_1_1geolocation.html", null ],
        [ "rapp::cloud::hazard_detection_door_check", "classrapp_1_1cloud_1_1hazard__detection__door__check.html", null ],
        [ "rapp::cloud::hazard_detection_light_check", "classrapp_1_1cloud_1_1hazard__detection__light__check.html", null ],
        [ "rapp::cloud::human_detection", "classrapp_1_1cloud_1_1human__detection.html", null ],
        [ "rapp::cloud::login_user", "classrapp_1_1cloud_1_1login__user.html", null ],
        [ "rapp::cloud::news_explore", "classrapp_1_1cloud_1_1news__explore.html", null ],
        [ "rapp::cloud::object_recognition", "classrapp_1_1cloud_1_1object__recognition.html", null ],
        [ "rapp::cloud::ontology_is_subsuperclass_of", "classrapp_1_1cloud_1_1ontology__is__subsuperclass__of.html", null ],
        [ "rapp::cloud::ontology_subclasses_of", "classrapp_1_1cloud_1_1ontology__subclasses__of.html", null ],
        [ "rapp::cloud::ontology_superclasses_of", "classrapp_1_1cloud_1_1ontology__superclasses__of.html", null ],
        [ "rapp::cloud::path_upload_map", "classrapp_1_1cloud_1_1path__upload__map.html", null ],
        [ "rapp::cloud::plan_path_2d", "classrapp_1_1cloud_1_1plan__path__2d.html", null ],
        [ "rapp::cloud::qr_detection", "classrapp_1_1cloud_1_1qr__detection.html", null ],
        [ "rapp::cloud::set_denoise_profile", "classrapp_1_1cloud_1_1set__denoise__profile.html", null ],
        [ "rapp::cloud::speech_detection_google", "classrapp_1_1cloud_1_1speech__detection__google.html", null ],
        [ "rapp::cloud::speech_detection_sphinx4", "classrapp_1_1cloud_1_1speech__detection__sphinx4.html", null ],
        [ "rapp::cloud::text_to_speech", "classrapp_1_1cloud_1_1text__to__speech.html", null ],
        [ "rapp::cloud::weather_report_current", "classrapp_1_1cloud_1_1weather__report__current.html", null ],
        [ "rapp::cloud::weather_report_forecast", "classrapp_1_1cloud_1_1weather__report__forecast.html", null ]
      ] ],
      [ "rapp::cloud::asio_socket_https", "classrapp_1_1cloud_1_1asio__socket__https.html", null ]
    ] ],
    [ "asio_service_http", null, [
      [ "rapp::cloud::fetch_personal_data", "classrapp_1_1cloud_1_1fetch__personal__data.html", null ]
    ] ],
    [ "rapp::cloud::asio_socket", "classrapp_1_1cloud_1_1asio__socket.html", [
      [ "rapp::cloud::asio_service_http", "classrapp_1_1cloud_1_1asio__service__http.html", null ],
      [ "rapp::cloud::asio_socket_https", "classrapp_1_1cloud_1_1asio__socket__https.html", null ]
    ] ],
    [ "rapp::object::audio", "classrapp_1_1object_1_1audio.html", [
      [ "rapp::object::microphone_wav", "classrapp_1_1object_1_1microphone__wav.html", null ],
      [ "rapp::object::nao_quad_channel_wav", "classrapp_1_1object_1_1nao__quad__channel__wav.html", null ],
      [ "rapp::object::nao_single_channel_wav", "classrapp_1_1object_1_1nao__single__channel__wav.html", null ],
      [ "rapp::object::ogg", "classrapp_1_1object_1_1ogg.html", null ]
    ] ],
    [ "CloudMsg", null, [
      [ "RappCloud.CloudMsgs.CognitiveExerciseSelect.CognitiveExerciseSelect", "classRappCloud_1_1CloudMsgs_1_1CognitiveExerciseSelect_1_1CognitiveExerciseSelect.html", null ],
      [ "RappCloud.CloudMsgs.CognitiveGetHistory.CognitiveGetHistory", "classRappCloud_1_1CloudMsgs_1_1CognitiveGetHistory_1_1CognitiveGetHistory.html", null ],
      [ "RappCloud.CloudMsgs.CognitiveGetScores.CognitiveGetScores", "classRappCloud_1_1CloudMsgs_1_1CognitiveGetScores_1_1CognitiveGetScores.html", null ],
      [ "RappCloud.CloudMsgs.CognitiveRecordPerformance.CognitiveRecordPerformance", "classRappCloud_1_1CloudMsgs_1_1CognitiveRecordPerformance_1_1CognitiveRecordPerformance.html", null ],
      [ "RappCloud.CloudMsgs.EmailFetch.EmailFetch", "classRappCloud_1_1CloudMsgs_1_1EmailFetch_1_1EmailFetch.html", null ],
      [ "RappCloud.CloudMsgs.EmailSend.EmailSend", "classRappCloud_1_1CloudMsgs_1_1EmailSend_1_1EmailSend.html", null ],
      [ "RappCloud.CloudMsgs.FaceDetection.FaceDetection", "classRappCloud_1_1CloudMsgs_1_1FaceDetection_1_1FaceDetection.html", null ],
      [ "RappCloud.CloudMsgs.Geolocation.Geolocation", "classRappCloud_1_1CloudMsgs_1_1Geolocation_1_1Geolocation.html", null ],
      [ "RappCloud.CloudMsgs.HazardDetectionDoor.HazardDetectionDoor", "classRappCloud_1_1CloudMsgs_1_1HazardDetectionDoor_1_1HazardDetectionDoor.html", null ],
      [ "RappCloud.CloudMsgs.HazardDetectionLight.HazardDetectionLight", "classRappCloud_1_1CloudMsgs_1_1HazardDetectionLight_1_1HazardDetectionLight.html", null ],
      [ "RappCloud.CloudMsgs.HumanDetection.HumanDetection", "classRappCloud_1_1CloudMsgs_1_1HumanDetection_1_1HumanDetection.html", null ],
      [ "RappCloud.CloudMsgs.NewsExplore.NewsExplore", "classRappCloud_1_1CloudMsgs_1_1NewsExplore_1_1NewsExplore.html", null ],
      [ "RappCloud.CloudMsgs.ObjectRecognitionCaffe.ObjectRecognitionCaffe", "classRappCloud_1_1CloudMsgs_1_1ObjectRecognitionCaffe_1_1ObjectRecognitionCaffe.html", null ],
      [ "RappCloud.CloudMsgs.OntologyIsSubsuperclass.OntologyIsSubsuperclass", "classRappCloud_1_1CloudMsgs_1_1OntologyIsSubsuperclass_1_1OntologyIsSubsuperclass.html", null ],
      [ "RappCloud.CloudMsgs.OntologySubclasses.OntologySubclasses", "classRappCloud_1_1CloudMsgs_1_1OntologySubclasses_1_1OntologySubclasses.html", null ],
      [ "RappCloud.CloudMsgs.OntologySuperclasses.OntologySuperclasses", "classRappCloud_1_1CloudMsgs_1_1OntologySuperclasses_1_1OntologySuperclasses.html", null ],
      [ "RappCloud.CloudMsgs.PathPlanningPlan2D.PathPlanningPlan2D", "classRappCloud_1_1CloudMsgs_1_1PathPlanningPlan2D_1_1PathPlanningPlan2D.html", null ],
      [ "RappCloud.CloudMsgs.PathPlanningUploadMap.PathPlanningUploadMap", "classRappCloud_1_1CloudMsgs_1_1PathPlanningUploadMap_1_1PathPlanningUploadMap.html", null ],
      [ "RappCloud.CloudMsgs.QrDetection.QrDetection", "classRappCloud_1_1CloudMsgs_1_1QrDetection_1_1QrDetection.html", null ],
      [ "RappCloud.CloudMsgs.SetNoiseProfile.SetNoiseProfile", "classRappCloud_1_1CloudMsgs_1_1SetNoiseProfile_1_1SetNoiseProfile.html", null ],
      [ "RappCloud.CloudMsgs.SpeechRecognitionGoogle.SpeechRecognitionGoogle", "classRappCloud_1_1CloudMsgs_1_1SpeechRecognitionGoogle_1_1SpeechRecognitionGoogle.html", null ],
      [ "RappCloud.CloudMsgs.SpeechRecognitionSphinx.SpeechRecognitionSphinx", "classRappCloud_1_1CloudMsgs_1_1SpeechRecognitionSphinx_1_1SpeechRecognitionSphinx.html", null ],
      [ "RappCloud.CloudMsgs.TextToSpeech.TextToSpeech", "classRappCloud_1_1CloudMsgs_1_1TextToSpeech_1_1TextToSpeech.html", null ],
      [ "RappCloud.CloudMsgs.WeatherReportCurrent.WeatherReportCurrent", "classRappCloud_1_1CloudMsgs_1_1WeatherReportCurrent_1_1WeatherReportCurrent.html", null ],
      [ "RappCloud.CloudMsgs.WeatherReportForecast.WeatherReportForecast", "classRappCloud_1_1CloudMsgs_1_1WeatherReportForecast_1_1WeatherReportForecast.html", null ]
    ] ],
    [ "CloudRequest", null, [
      [ "RappCloud.CloudMsgs.CognitiveExerciseSelect.CognitiveExerciseSelect.Request", "classRappCloud_1_1CloudMsgs_1_1CognitiveExerciseSelect_1_1CognitiveExerciseSelect_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.CognitiveGetHistory.CognitiveGetHistory.Request", "classRappCloud_1_1CloudMsgs_1_1CognitiveGetHistory_1_1CognitiveGetHistory_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.CognitiveGetScores.CognitiveGetScores.Request", "classRappCloud_1_1CloudMsgs_1_1CognitiveGetScores_1_1CognitiveGetScores_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.CognitiveRecordPerformance.CognitiveRecordPerformance.Request", "classRappCloud_1_1CloudMsgs_1_1CognitiveRecordPerformance_1_1CognitiveRecordPerformance_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.EmailFetch.EmailFetch.Request", "classRappCloud_1_1CloudMsgs_1_1EmailFetch_1_1EmailFetch_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.EmailSend.EmailSend.Request", "classRappCloud_1_1CloudMsgs_1_1EmailSend_1_1EmailSend_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.FaceDetection.FaceDetection.Request", "classRappCloud_1_1CloudMsgs_1_1FaceDetection_1_1FaceDetection_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.Geolocation.Geolocation.Request", "classRappCloud_1_1CloudMsgs_1_1Geolocation_1_1Geolocation_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.HazardDetectionDoor.HazardDetectionDoor.Request", "classRappCloud_1_1CloudMsgs_1_1HazardDetectionDoor_1_1HazardDetectionDoor_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.HazardDetectionLight.HazardDetectionLight.Request", "classRappCloud_1_1CloudMsgs_1_1HazardDetectionLight_1_1HazardDetectionLight_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.HumanDetection.HumanDetection.Request", "classRappCloud_1_1CloudMsgs_1_1HumanDetection_1_1HumanDetection_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.NewsExplore.NewsExplore.Request", "classRappCloud_1_1CloudMsgs_1_1NewsExplore_1_1NewsExplore_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.ObjectRecognitionCaffe.ObjectRecognitionCaffe.Request", "classRappCloud_1_1CloudMsgs_1_1ObjectRecognitionCaffe_1_1ObjectRecognitionCaffe_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.OntologyIsSubsuperclass.OntologyIsSubsuperclass.Request", "classRappCloud_1_1CloudMsgs_1_1OntologyIsSubsuperclass_1_1OntologyIsSubsuperclass_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.OntologySubclasses.OntologySubclasses.Request", "classRappCloud_1_1CloudMsgs_1_1OntologySubclasses_1_1OntologySubclasses_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.OntologySuperclasses.OntologySuperclasses.Request", "classRappCloud_1_1CloudMsgs_1_1OntologySuperclasses_1_1OntologySuperclasses_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.PathPlanningPlan2D.PathPlanningPlan2D.Request", "classRappCloud_1_1CloudMsgs_1_1PathPlanningPlan2D_1_1PathPlanningPlan2D_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.PathPlanningUploadMap.PathPlanningUploadMap.Request", "classRappCloud_1_1CloudMsgs_1_1PathPlanningUploadMap_1_1PathPlanningUploadMap_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.QrDetection.QrDetection.Request", "classRappCloud_1_1CloudMsgs_1_1QrDetection_1_1QrDetection_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.SetNoiseProfile.SetNoiseProfile.Request", "classRappCloud_1_1CloudMsgs_1_1SetNoiseProfile_1_1SetNoiseProfile_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.SpeechRecognitionGoogle.SpeechRecognitionGoogle.Request", "classRappCloud_1_1CloudMsgs_1_1SpeechRecognitionGoogle_1_1SpeechRecognitionGoogle_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.SpeechRecognitionSphinx.SpeechRecognitionSphinx.Request", "classRappCloud_1_1CloudMsgs_1_1SpeechRecognitionSphinx_1_1SpeechRecognitionSphinx_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.TextToSpeech.TextToSpeech.Request", "classRappCloud_1_1CloudMsgs_1_1TextToSpeech_1_1TextToSpeech_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.WeatherReportCurrent.WeatherReportCurrent.Request", "classRappCloud_1_1CloudMsgs_1_1WeatherReportCurrent_1_1WeatherReportCurrent_1_1Request.html", null ],
      [ "RappCloud.CloudMsgs.WeatherReportForecast.WeatherReportForecast.Request", "classRappCloud_1_1CloudMsgs_1_1WeatherReportForecast_1_1WeatherReportForecast_1_1Request.html", null ]
    ] ],
    [ "CloudResponse", null, [
      [ "RappCloud.CloudMsgs.CognitiveExerciseSelect.CognitiveExerciseSelect.Response", "classRappCloud_1_1CloudMsgs_1_1CognitiveExerciseSelect_1_1CognitiveExerciseSelect_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.CognitiveGetHistory.CognitiveGetHistory.Response", "classRappCloud_1_1CloudMsgs_1_1CognitiveGetHistory_1_1CognitiveGetHistory_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.CognitiveGetScores.CognitiveGetScores.Response", "classRappCloud_1_1CloudMsgs_1_1CognitiveGetScores_1_1CognitiveGetScores_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.CognitiveRecordPerformance.CognitiveRecordPerformance.Response", "classRappCloud_1_1CloudMsgs_1_1CognitiveRecordPerformance_1_1CognitiveRecordPerformance_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.EmailFetch.EmailFetch.Response", "classRappCloud_1_1CloudMsgs_1_1EmailFetch_1_1EmailFetch_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.EmailSend.EmailSend.Response", "classRappCloud_1_1CloudMsgs_1_1EmailSend_1_1EmailSend_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.FaceDetection.FaceDetection.Response", "classRappCloud_1_1CloudMsgs_1_1FaceDetection_1_1FaceDetection_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.Geolocation.Geolocation.Response", "classRappCloud_1_1CloudMsgs_1_1Geolocation_1_1Geolocation_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.HazardDetectionDoor.HazardDetectionDoor.Response", "classRappCloud_1_1CloudMsgs_1_1HazardDetectionDoor_1_1HazardDetectionDoor_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.HazardDetectionLight.HazardDetectionLight.Response", "classRappCloud_1_1CloudMsgs_1_1HazardDetectionLight_1_1HazardDetectionLight_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.HumanDetection.HumanDetection.Response", "classRappCloud_1_1CloudMsgs_1_1HumanDetection_1_1HumanDetection_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.NewsExplore.NewsExplore.Response", "classRappCloud_1_1CloudMsgs_1_1NewsExplore_1_1NewsExplore_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.ObjectRecognitionCaffe.ObjectRecognitionCaffe.Response", "classRappCloud_1_1CloudMsgs_1_1ObjectRecognitionCaffe_1_1ObjectRecognitionCaffe_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.OntologyIsSubsuperclass.OntologyIsSubsuperclass.Response", "classRappCloud_1_1CloudMsgs_1_1OntologyIsSubsuperclass_1_1OntologyIsSubsuperclass_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.OntologySubclasses.OntologySubclasses.Response", "classRappCloud_1_1CloudMsgs_1_1OntologySubclasses_1_1OntologySubclasses_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.OntologySuperclasses.OntologySuperclasses.Response", "classRappCloud_1_1CloudMsgs_1_1OntologySuperclasses_1_1OntologySuperclasses_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.PathPlanningPlan2D.PathPlanningPlan2D.Response", "classRappCloud_1_1CloudMsgs_1_1PathPlanningPlan2D_1_1PathPlanningPlan2D_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.PathPlanningUploadMap.PathPlanningUploadMap.Response", "classRappCloud_1_1CloudMsgs_1_1PathPlanningUploadMap_1_1PathPlanningUploadMap_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.QrDetection.QrDetection.Response", "classRappCloud_1_1CloudMsgs_1_1QrDetection_1_1QrDetection_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.SetNoiseProfile.SetNoiseProfile.Response", "classRappCloud_1_1CloudMsgs_1_1SetNoiseProfile_1_1SetNoiseProfile_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.SpeechRecognitionGoogle.SpeechRecognitionGoogle.Response", "classRappCloud_1_1CloudMsgs_1_1SpeechRecognitionGoogle_1_1SpeechRecognitionGoogle_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.SpeechRecognitionSphinx.SpeechRecognitionSphinx.Response", "classRappCloud_1_1CloudMsgs_1_1SpeechRecognitionSphinx_1_1SpeechRecognitionSphinx_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.TextToSpeech.TextToSpeech.Response", "classRappCloud_1_1CloudMsgs_1_1TextToSpeech_1_1TextToSpeech_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.WeatherReportCurrent.WeatherReportCurrent.Response", "classRappCloud_1_1CloudMsgs_1_1WeatherReportCurrent_1_1WeatherReportCurrent_1_1Response.html", null ],
      [ "RappCloud.CloudMsgs.WeatherReportForecast.WeatherReportForecast.Response", "classRappCloud_1_1CloudMsgs_1_1WeatherReportForecast_1_1WeatherReportForecast_1_1Response.html", null ]
    ] ],
    [ "rapp::object::face", "classrapp_1_1object_1_1face.html", null ],
    [ "rapp::object::human", "classrapp_1_1object_1_1human.html", null ],
    [ "object", null, [
      [ "RappCloud.CloudMsgs.Cloud.CloudMsg", "classRappCloud_1_1CloudMsgs_1_1Cloud_1_1CloudMsg.html", null ],
      [ "RappCloud.CloudMsgs.Cloud.CloudRequest", "classRappCloud_1_1CloudMsgs_1_1Cloud_1_1CloudRequest.html", null ],
      [ "RappCloud.CloudMsgs.Cloud.CloudResponse", "classRappCloud_1_1CloudMsgs_1_1Cloud_1_1CloudResponse.html", null ],
      [ "RappCloud.Objects.File.File", "classRappCloud_1_1Objects_1_1File_1_1File.html", null ],
      [ "RappCloud.Objects.Payload.Payload", "classRappCloud_1_1Objects_1_1Payload_1_1Payload.html", null ],
      [ "RappCloud.Service.RappPlatformService.RappPlatformService", "classRappCloud_1_1Service_1_1RappPlatformService_1_1RappPlatformService.html", null ],
      [ "RappCloud.ServiceController.AsyncHandler.AsyncHandler", "classRappCloud_1_1ServiceController_1_1AsyncHandler_1_1AsyncHandler.html", null ],
      [ "RappCloud.ServiceController.ServiceControllerBase.ServiceControllerBase", "classRappCloud_1_1ServiceController_1_1ServiceControllerBase_1_1ServiceControllerBase.html", [
        [ "RappCloud.ServiceController.ServiceControllerAsync.ServiceControllerAsync", "classRappCloud_1_1ServiceController_1_1ServiceControllerAsync_1_1ServiceControllerAsync.html", null ],
        [ "RappCloud.ServiceController.ServiceControllerSync.ServiceControllerSync", "classRappCloud_1_1ServiceController_1_1ServiceControllerSync_1_1ServiceControllerSync.html", null ]
      ] ],
      [ "RappCloud.Utils.Net.Net", "classRappCloud_1_1Utils_1_1Net_1_1Net.html", null ]
    ] ],
    [ "rapp::object::picture", "classrapp_1_1object_1_1picture.html", null ],
    [ "plan_path2d", "classplan__path2d.html", null ],
    [ "rapp::object::qr_code", "classrapp_1_1object_1_1qr__code.html", null ],
    [ "qrCode", "classqrCode.html", null ],
    [ "RappCloud.Utils.RandStrGen.RandStrGen", "classRappCloud_1_1Utils_1_1RandStrGen_1_1RandStrGen.html", null ],
    [ "RappCloud.RappPlatformApi.RappPlatformAPI", "classRappCloud_1_1RappPlatformApi_1_1RappPlatformAPI.html", null ],
    [ "rapp::cloud::service_controller", "classrapp_1_1cloud_1_1service__controller.html", null ],
    [ "RappCloud.ServiceController.Adapters.SSLDef", "classRappCloud_1_1ServiceController_1_1Adapters_1_1SSLDef.html", null ],
    [ "AuthBase", null, [
      [ "RappCloud.ServiceController.RAPPAuth.RAPPAuth", "classRappCloud_1_1ServiceController_1_1RAPPAuth_1_1RAPPAuth.html", null ]
    ] ],
    [ "HTTPAdapter", null, [
      [ "RappCloud.ServiceController.Adapters.SSLAdapter", "classRappCloud_1_1ServiceController_1_1Adapters_1_1SSLAdapter.html", [
        [ "RappCloud.ServiceController.Adapters.SSL23Adapter", "classRappCloud_1_1ServiceController_1_1Adapters_1_1SSL23Adapter.html", null ],
        [ "RappCloud.ServiceController.Adapters.SSL2Adapter", "classRappCloud_1_1ServiceController_1_1Adapters_1_1SSL2Adapter.html", null ],
        [ "RappCloud.ServiceController.Adapters.SSL3Adapter", "classRappCloud_1_1ServiceController_1_1Adapters_1_1SSL3Adapter.html", null ],
        [ "RappCloud.ServiceController.Adapters.TLS11Adapter", "classRappCloud_1_1ServiceController_1_1Adapters_1_1TLS11Adapter.html", null ],
        [ "RappCloud.ServiceController.Adapters.TLS12Adapter", "classRappCloud_1_1ServiceController_1_1Adapters_1_1TLS12Adapter.html", null ],
        [ "RappCloud.ServiceController.Adapters.TLS1Adapter", "classRappCloud_1_1ServiceController_1_1Adapters_1_1TLS1Adapter.html", null ],
        [ "RappCloud.ServiceController.Adapters.TLSAdapter", "classRappCloud_1_1ServiceController_1_1Adapters_1_1TLSAdapter.html", null ]
      ] ]
    ] ]
];