var namespaceRappCloud_1_1CloudMsgs =
[
    [ "Cloud", "namespaceRappCloud_1_1CloudMsgs_1_1Cloud.html", "namespaceRappCloud_1_1CloudMsgs_1_1Cloud" ],
    [ "CognitiveExerciseSelect", "namespaceRappCloud_1_1CloudMsgs_1_1CognitiveExerciseSelect.html", "namespaceRappCloud_1_1CloudMsgs_1_1CognitiveExerciseSelect" ],
    [ "CognitiveGetHistory", "namespaceRappCloud_1_1CloudMsgs_1_1CognitiveGetHistory.html", "namespaceRappCloud_1_1CloudMsgs_1_1CognitiveGetHistory" ],
    [ "CognitiveGetScores", "namespaceRappCloud_1_1CloudMsgs_1_1CognitiveGetScores.html", "namespaceRappCloud_1_1CloudMsgs_1_1CognitiveGetScores" ],
    [ "CognitiveRecordPerformance", "namespaceRappCloud_1_1CloudMsgs_1_1CognitiveRecordPerformance.html", "namespaceRappCloud_1_1CloudMsgs_1_1CognitiveRecordPerformance" ],
    [ "EmailFetch", "namespaceRappCloud_1_1CloudMsgs_1_1EmailFetch.html", "namespaceRappCloud_1_1CloudMsgs_1_1EmailFetch" ],
    [ "EmailSend", "namespaceRappCloud_1_1CloudMsgs_1_1EmailSend.html", "namespaceRappCloud_1_1CloudMsgs_1_1EmailSend" ],
    [ "FaceDetection", "namespaceRappCloud_1_1CloudMsgs_1_1FaceDetection.html", "namespaceRappCloud_1_1CloudMsgs_1_1FaceDetection" ],
    [ "Geolocation", "namespaceRappCloud_1_1CloudMsgs_1_1Geolocation.html", "namespaceRappCloud_1_1CloudMsgs_1_1Geolocation" ],
    [ "HazardDetectionDoor", "namespaceRappCloud_1_1CloudMsgs_1_1HazardDetectionDoor.html", "namespaceRappCloud_1_1CloudMsgs_1_1HazardDetectionDoor" ],
    [ "HazardDetectionLight", "namespaceRappCloud_1_1CloudMsgs_1_1HazardDetectionLight.html", "namespaceRappCloud_1_1CloudMsgs_1_1HazardDetectionLight" ],
    [ "HumanDetection", "namespaceRappCloud_1_1CloudMsgs_1_1HumanDetection.html", "namespaceRappCloud_1_1CloudMsgs_1_1HumanDetection" ],
    [ "NewsExplore", "namespaceRappCloud_1_1CloudMsgs_1_1NewsExplore.html", "namespaceRappCloud_1_1CloudMsgs_1_1NewsExplore" ],
    [ "ObjectRecognitionCaffe", "namespaceRappCloud_1_1CloudMsgs_1_1ObjectRecognitionCaffe.html", "namespaceRappCloud_1_1CloudMsgs_1_1ObjectRecognitionCaffe" ],
    [ "OntologyIsSubsuperclass", "namespaceRappCloud_1_1CloudMsgs_1_1OntologyIsSubsuperclass.html", "namespaceRappCloud_1_1CloudMsgs_1_1OntologyIsSubsuperclass" ],
    [ "OntologySubclasses", "namespaceRappCloud_1_1CloudMsgs_1_1OntologySubclasses.html", "namespaceRappCloud_1_1CloudMsgs_1_1OntologySubclasses" ],
    [ "OntologySuperclasses", "namespaceRappCloud_1_1CloudMsgs_1_1OntologySuperclasses.html", "namespaceRappCloud_1_1CloudMsgs_1_1OntologySuperclasses" ],
    [ "PathPlanningPlan2D", "namespaceRappCloud_1_1CloudMsgs_1_1PathPlanningPlan2D.html", "namespaceRappCloud_1_1CloudMsgs_1_1PathPlanningPlan2D" ],
    [ "PathPlanningUploadMap", "namespaceRappCloud_1_1CloudMsgs_1_1PathPlanningUploadMap.html", "namespaceRappCloud_1_1CloudMsgs_1_1PathPlanningUploadMap" ],
    [ "QrDetection", "namespaceRappCloud_1_1CloudMsgs_1_1QrDetection.html", "namespaceRappCloud_1_1CloudMsgs_1_1QrDetection" ],
    [ "SetNoiseProfile", "namespaceRappCloud_1_1CloudMsgs_1_1SetNoiseProfile.html", "namespaceRappCloud_1_1CloudMsgs_1_1SetNoiseProfile" ],
    [ "SpeechRecognitionGoogle", "namespaceRappCloud_1_1CloudMsgs_1_1SpeechRecognitionGoogle.html", "namespaceRappCloud_1_1CloudMsgs_1_1SpeechRecognitionGoogle" ],
    [ "SpeechRecognitionSphinx", "namespaceRappCloud_1_1CloudMsgs_1_1SpeechRecognitionSphinx.html", "namespaceRappCloud_1_1CloudMsgs_1_1SpeechRecognitionSphinx" ],
    [ "TextToSpeech", "namespaceRappCloud_1_1CloudMsgs_1_1TextToSpeech.html", "namespaceRappCloud_1_1CloudMsgs_1_1TextToSpeech" ],
    [ "WeatherReportCurrent", "namespaceRappCloud_1_1CloudMsgs_1_1WeatherReportCurrent.html", "namespaceRappCloud_1_1CloudMsgs_1_1WeatherReportCurrent" ],
    [ "WeatherReportForecast", "namespaceRappCloud_1_1CloudMsgs_1_1WeatherReportForecast.html", "namespaceRappCloud_1_1CloudMsgs_1_1WeatherReportForecast" ]
];