var namespacerapp_1_1cloud =
[
    [ "asio_handler", "classrapp_1_1cloud_1_1asio__handler.html", "classrapp_1_1cloud_1_1asio__handler" ],
    [ "asio_service_http", "classrapp_1_1cloud_1_1asio__service__http.html", "classrapp_1_1cloud_1_1asio__service__http" ],
    [ "asio_socket", "classrapp_1_1cloud_1_1asio__socket.html", "classrapp_1_1cloud_1_1asio__socket" ],
    [ "asio_socket_https", "classrapp_1_1cloud_1_1asio__socket__https.html", "classrapp_1_1cloud_1_1asio__socket__https" ],
    [ "available_services", "classrapp_1_1cloud_1_1available__services.html", "classrapp_1_1cloud_1_1available__services" ],
    [ "cognitive_get_history", "classrapp_1_1cloud_1_1cognitive__get__history.html", "classrapp_1_1cloud_1_1cognitive__get__history" ],
    [ "cognitive_get_scores", "classrapp_1_1cloud_1_1cognitive__get__scores.html", "classrapp_1_1cloud_1_1cognitive__get__scores" ],
    [ "cognitive_record_performance", "classrapp_1_1cloud_1_1cognitive__record__performance.html", "classrapp_1_1cloud_1_1cognitive__record__performance" ],
    [ "cognitive_test_selector", "classrapp_1_1cloud_1_1cognitive__test__selector.html", "classrapp_1_1cloud_1_1cognitive__test__selector" ],
    [ "email_fetch", "classrapp_1_1cloud_1_1email__fetch.html", "classrapp_1_1cloud_1_1email__fetch" ],
    [ "email_send", "classrapp_1_1cloud_1_1email__send.html", "classrapp_1_1cloud_1_1email__send" ],
    [ "face_detection", "classrapp_1_1cloud_1_1face__detection.html", "classrapp_1_1cloud_1_1face__detection" ],
    [ "fetch_personal_data", "classrapp_1_1cloud_1_1fetch__personal__data.html", "classrapp_1_1cloud_1_1fetch__personal__data" ],
    [ "geolocation", "classrapp_1_1cloud_1_1geolocation.html", "classrapp_1_1cloud_1_1geolocation" ],
    [ "hazard_detection_door_check", "classrapp_1_1cloud_1_1hazard__detection__door__check.html", "classrapp_1_1cloud_1_1hazard__detection__door__check" ],
    [ "hazard_detection_light_check", "classrapp_1_1cloud_1_1hazard__detection__light__check.html", "classrapp_1_1cloud_1_1hazard__detection__light__check" ],
    [ "human_detection", "classrapp_1_1cloud_1_1human__detection.html", "classrapp_1_1cloud_1_1human__detection" ],
    [ "login_user", "classrapp_1_1cloud_1_1login__user.html", "classrapp_1_1cloud_1_1login__user" ],
    [ "news_explore", "classrapp_1_1cloud_1_1news__explore.html", "classrapp_1_1cloud_1_1news__explore" ],
    [ "object_recognition", "classrapp_1_1cloud_1_1object__recognition.html", "classrapp_1_1cloud_1_1object__recognition" ],
    [ "ontology_is_subsuperclass_of", "classrapp_1_1cloud_1_1ontology__is__subsuperclass__of.html", "classrapp_1_1cloud_1_1ontology__is__subsuperclass__of" ],
    [ "ontology_subclasses_of", "classrapp_1_1cloud_1_1ontology__subclasses__of.html", "classrapp_1_1cloud_1_1ontology__subclasses__of" ],
    [ "ontology_superclasses_of", "classrapp_1_1cloud_1_1ontology__superclasses__of.html", "classrapp_1_1cloud_1_1ontology__superclasses__of" ],
    [ "path_upload_map", "classrapp_1_1cloud_1_1path__upload__map.html", null ],
    [ "plan_path_2d", "classrapp_1_1cloud_1_1plan__path__2d.html", "classrapp_1_1cloud_1_1plan__path__2d" ],
    [ "qr_detection", "classrapp_1_1cloud_1_1qr__detection.html", "classrapp_1_1cloud_1_1qr__detection" ],
    [ "service_controller", "classrapp_1_1cloud_1_1service__controller.html", "classrapp_1_1cloud_1_1service__controller" ],
    [ "set_denoise_profile", "classrapp_1_1cloud_1_1set__denoise__profile.html", "classrapp_1_1cloud_1_1set__denoise__profile" ],
    [ "speech_detection_google", "classrapp_1_1cloud_1_1speech__detection__google.html", "classrapp_1_1cloud_1_1speech__detection__google" ],
    [ "speech_detection_sphinx4", "classrapp_1_1cloud_1_1speech__detection__sphinx4.html", "classrapp_1_1cloud_1_1speech__detection__sphinx4" ],
    [ "text_to_speech", "classrapp_1_1cloud_1_1text__to__speech.html", "classrapp_1_1cloud_1_1text__to__speech" ],
    [ "weather_report_current", "classrapp_1_1cloud_1_1weather__report__current.html", "classrapp_1_1cloud_1_1weather__report__current" ],
    [ "weather_report_forecast", "classrapp_1_1cloud_1_1weather__report__forecast.html", "classrapp_1_1cloud_1_1weather__report__forecast" ]
];