
/* @bug Sometimes the websocket implementation from hop gets undefined before
 * the onmessage event calls
 */

hop = require('hop');
fs = require('fs');

var user = process.env.LOGNAME;
var storePath = "/home/" + user + "/hop_temps/"; 
var rosService = "/ric/speech_detection_sphinx4_batch";
var randStringGen = require('../utilities/./randStringGen.js');

/*----<Random String Generator configurations---->*/
var stringLength = 5;
var randStrGen = new randStringGen( stringLength );
/*------------------------------------------------*/


service speech_detection_sphinx4( {fileUrl: '', language: '', audio_source: '', words: [], sentences: [], grammar: [], user: ''} ){
  console.log('Service invocation. Preparing response');
  console.log('Audio source file stored at:', fileUrl);
  console.log('Words to search for:', words);
  console.log('Sentences:', sentences);
  console.log('Grammar:', grammar);

  /* --< Perform renaming on the reived file. Add uniqueId value> --- */
  var unqExt = randStrGen.createUnique();
  randStrGen.removeCached(unqExt);
  var file = fileUrl.split('.');
  var fileUri_new = file[0] + '.' + file[1] +  unqExt + '.' + file[2]
    fs.renameSync(fileUrl, fileUri_new);
  /*----------------------------------------------------------------- */
  var respFlag = false;
  return hop.HTTPResponseAsync(
    function( sendResponse ) { 
      // sendResponse is a function argument that is generated by Hop to complete the service when the response is ready
      // here you need to send a message to rosbridge, prepare a callback to handle the result, and then  sendResponse( result ) in the callback body to actually return the service result.
      //var fileName = "speech-" + "bitch" + ".wav";
      //var audioFileUrl = Fs.resolvePath( storePath + fileName );
      //Fs.writeFileSync( audioFileUrl, fileData );
      console.log(typeof words)
      var args = {
        'path': /*audioFileUrl*/fileUri_new,
        'audio_source': audio_source,
        'words': JSON.parse(words),
        'sentences': JSON.parse(sentences),
        'grammar': JSON.parse(grammar),
        'language': language,
        'user': user
      };

      var uniqueID = randStrGen.createUnique();
      var ros_srv_call = {
        'op': 'call_service',
        'service': rosService,
        'args': args,
        'id': uniqueID
      };

      var rosWS = new WebSocket('ws://localhost:9090');
      rosWS.onopen = function(){
        console.log('Connection to rosbridge established');
        this.send(JSON.stringify(ros_srv_call));
      }
      rosWS.onclose = function(){
        console.log('Connection to rosbridge closed');
      }
      rosWS.onmessage = function(event){
        console.log('Received message from rosbridge');
        var resp_msg = event.value;
        sendResponse( resp_msg );
        console.log(resp_msg);
        this.close();
        rosWS = undefined;
        respFlag = true;
        randStrGen.removeCached( uniqueID );
      }

      function asyncWrap(){
        setTimeout( function(){
          if (respFlag != true){
            console.log('Connection timed out! rosWs = undefined');
            //sendResponse('Timeout');
            if (rosWS != undefined)
            {
              rosWS.close();
            }
            rosWS = undefined;
            /* --< Re-open connection to the WebSocket >--*/
            rosWS = new WebSocket('ws://localhost:9090');
            /* -----------< Redefine WebSocket callbacks >----------- */
            rosWS.onopen = function(){
              console.log('Connection to rosbridge established');
              this.send(JSON.stringify(ros_srv_call));
            }

            rosWS.onclose = function(){
              console.log('Connection to rosbridge closed');
            }

            rosWS.onmessage = function(event){
              console.log('Received message from rosbridge');
              var resp_msg = event.value; 
              sendResponse( resp_msg ); //Return response to client
              console.log(resp_msg);
              this.close(); // Close the connection to the websocket
              rosWS = undefined; // Decostruct the websocket object
              respFlag = true;
              randStrGen.removeCached( uniqueID ); //Remove the uniqueID so it can be reused
            }
            /*--------------------------------------------------------*/
            asyncWrap();
          }
        }, 8000); //Timeout value is set at 10 seconds
      }
      asyncWrap();

    }, this ); // do not forget the <this> argument of hop.HTTResponseAsync 
}

