# Contains info about time and reference
Header header
# The image's filename to perform the detection
string imageFilename
---
# Container for detected qr positions
geometry_msgs/PointStamped[] qr_centers
string[] qr_messages
