var namespacerapp__speech__detection__sphinx4_1_1speech__recognition__sphinx4__handler__node =
[
    [ "SpeechRecognitionSphinx4HandlerNode", "classrapp__speech__detection__sphinx4_1_1speech__recognition__sphinx4__handler__node_1_1SpeechRecognitionSphinx4HandlerNode.html", "classrapp__speech__detection__sphinx4_1_1speech__recognition__sphinx4__handler__node_1_1SpeechRecognitionSphinx4HandlerNode" ]
];