var namespaces =
[
    [ "app_error_exception", "namespaceapp__error__exception.html", null ],
    [ "caffe_wrapper", "namespacecaffe__wrapper.html", null ],
    [ "caffe_wrapper_main", "namespacecaffe__wrapper__main.html", null ],
    [ "cognitive_exercise", "namespacecognitive__exercise.html", null ],
    [ "cognitive_exercise_main", "namespacecognitive__exercise__main.html", null ],
    [ "costmap_2d", "namespacecostmap__2d.html", null ],
    [ "crop_map", "namespacecrop__map.html", null ],
    [ "helper_functions", "namespacehelper__functions.html", null ],
    [ "image_classification", "namespaceimage__classification.html", null ],
    [ "image_registration_to_ontology", "namespaceimage__registration__to__ontology.html", null ],
    [ "map_server", "namespacemap__server.html", null ],
    [ "mysql_wrapper", "namespacemysql__wrapper.html", null ],
    [ "mysql_wrapper_main", "namespacemysql__wrapper__main.html", null ],
    [ "mysql_wrapper_old", "namespacemysql__wrapper__old.html", null ],
    [ "ontology_class_bridge", "namespaceontology__class__bridge.html", null ],
    [ "rapp_application_authentication_manager", "namespacerapp__application__authentication__manager.html", "namespacerapp__application__authentication__manager" ],
    [ "rapp_audio_processing", "namespacerapp__audio__processing.html", "namespacerapp__audio__processing" ],
    [ "rapp_email", "namespacerapp__email.html", "namespacerapp__email" ],
    [ "rapp_geolocator", "namespacerapp__geolocator.html", "namespacerapp__geolocator" ],
    [ "rapp_news_explorer", "namespacerapp__news__explorer.html", "namespacerapp__news__explorer" ],
    [ "rapp_speech_detection_sphinx4", "namespacerapp__speech__detection__sphinx4.html", "namespacerapp__speech__detection__sphinx4" ],
    [ "rapp_weather_reporter", "namespacerapp__weather__reporter.html", "namespacerapp__weather__reporter" ],
    [ "speech_recognition_google", "namespacespeech__recognition__google.html", null ],
    [ "src", "namespacesrc.html", "namespacesrc" ],
    [ "text_to_speech_espeak", "namespacetext__to__speech__espeak.html", null ],
    [ "userScoreHistoryForAllCategories", "namespaceuserScoreHistoryForAllCategories.html", null ],
    [ "userScoresForAllCategories", "namespaceuserScoresForAllCategories.html", null ]
];