var speech__recognition__sphinx4__handler__node_8py =
[
    [ "SpeechRecognitionSphinx4HandlerNode", "classrapp__speech__detection__sphinx4_1_1speech__recognition__sphinx4__handler__node_1_1SpeechRecognitionSphinx4HandlerNode.html", "classrapp__speech__detection__sphinx4_1_1speech__recognition__sphinx4__handler__node_1_1SpeechRecognitionSphinx4HandlerNode" ],
    [ "SpeechRecognitionSphinx4HandlerNode", "speech__recognition__sphinx4__handler__node_8py.html#ace55376f7271074fc9bcd18214509dbc", null ]
];