var namespacecognitive__exercise__system__services__functional__tests =
[
    [ "CognitiveExerciseFunc", "classcognitive__exercise__system__services__functional__tests_1_1CognitiveExerciseFunc.html", "classcognitive__exercise__system__services__functional__tests_1_1CognitiveExerciseFunc" ]
];