# Contains info about time and reference
Header header
# General string for simple queries
string instance_name
string[] attribute_names
string[] attribute_values
---
# The results of the query
string error
string[] trace
string[] confirmation
bool success 
string error
