# Contains info about time and reference
Header header
#the username of the user whose records will be cleared
string username
#specify clearing the records of this test type onle
string test_type
---
# The results of the query
#possible error
string error
#trace information
string[] trace
#true if service call was successful
bool success 
