# Contains info about time and reference
Header header
# General string for simple queries
string test_type
---
# The results of the query
string[] tests
string[] file_paths
string[] difficulty
string[] variation
string[] subtype
string[] trace
bool success 
string error
