# Contains info about time and reference
Header header
# General string for simple queries
string test_type
string test_language
---
# The results of the query
string[] tests
string[] file_paths
string[] difficulty
string[] subtype
string[] trace
bool success 
string error
