# Contains info about time and reference
Header header
# General string for simple queries
string username
string ontology_class
string file_url
string comments 
---
# The results of the query
string instance_name
string[] trace
bool success 
string error
