# Contains info about time and reference
Header header
# General string for simple queries
string test_type
int32 test_difficulty
int32 test_id
string test_path
string test_subtype
string[] supported_languages
---
# The results of the query
string test_name
string[] trace
bool success 
string error
