# Contains info about time and reference
Header header
# General string for simple queries
std_msgs/String ontology_class 
---
# The results of the query
std_msgs/String[] results 
std_msgs/String[] trace
bool success 
string error
