# Contains info about time and reference
Header header
# General string for simple queries
string parent_class 
string child_class
bool recursive
---
# The results of the query
string error
bool result 
string[] trace
bool success 
