# Contains info about time and reference
Header header
# General string for simple queries
string ontology_class 
string other_class
---
# The results of the query
string[] results 
string[] trace
bool success 
