# Contains info about time and reference
Header header
# The image's filename to perform human detection
string imageFilename
# Flag to define if a fast detection if desired
bool fast
---
# Container for detected human positions
geometry_msgs/PointStamped[] humans_up_left
geometry_msgs/PointStamped[] humans_down_right
string error
