var namespacecognitive__exercise__system__knowrob__services__functional__tests =
[
    [ "OntologyFunc", "classcognitive__exercise__system__knowrob__services__functional__tests_1_1OntologyFunc.html", "classcognitive__exercise__system__knowrob__services__functional__tests_1_1OntologyFunc" ]
];