# Contains info about time and reference
Header header
# The image's filename to perform face detection
string imageFilename
---
# Container for detected face positions
geometry_msgs/PointStamped[] faces_up_left
geometry_msgs/PointStamped[] faces_down_right
string error
