string email
string password
string server
string port

# Define which mails the users requests.
# Values: ALL, UNSEEN(DEFAULT)
string requestedEmailStatus

uint16 fromDate
uint16 toDate
uint16 numberOfEmails

---
# Response

# 0 success, -1 failure
int8 status

# The requested emails
rapp_platform_ros_communications/MailMsg[] emails
