# Rapp User
string username

# Define which mails the users requests.
# Values: ALL, UNREAD(DEFAULT)
string mailStatus

uint16 fromDate
uint16 toDate

---
# Response

# 0 success, -1 failure
int8 status

# The requested emails
rapp_platform_ros_communications/MailMsg[] emails
