string email
string password
# The email server's imap address, i.e. 'imap.gmail.com'
string server
# The email server imap port
string port

# Define which mails the users requests.
# Values: ALL, UNSEEN(DEFAULT)
string requestedEmailStatus

uint64 fromDate
uint64 toDate
uint16 numberOfEmails

---
# Response

# 0 success, -1 failure
int8 status

# The requested emails
rapp_platform_ros_communications/MailMsg[] emails
