# Request
string userEmail
string password
# The email server's smtp address, i.e. 'imap.gmail.com'
string server
# The email server smtp port
string port

# Email addresses of the recipients
string[] recipients

# The email body
string body
# The email subject
string subject

# File names of the attachments
string[] files

---

# Response

# 0 success, -1 failure
int8 status
