var dir_684416fdb99e45c7dea4941b3fbe2a50 =
[
    [ "email_fetch.py", "email__fetch_8py.html", "email__fetch_8py" ],
    [ "email_send_single_attach.py", "email__send__single__attach_8py.html", "email__send__single__attach_8py" ],
    [ "email_send_zip.py", "email__send__zip_8py.html", "email__send__zip_8py" ],
    [ "face_detection_test_close_angle.py", "face__detection__test__close__angle_8py.html", "face__detection__test__close__angle_8py" ],
    [ "face_detection_test_far_angle.py", "face__detection__test__far__angle_8py.html", "face__detection__test__far__angle_8py" ],
    [ "face_detection_test_far_straight.py", "face__detection__test__far__straight_8py.html", "face__detection__test__far__straight_8py" ],
    [ "face_detection_test_medium_angle.py", "face__detection__test__medium__angle_8py.html", "face__detection__test__medium__angle_8py" ],
    [ "face_detection_test_medium_straight.py", "face__detection__test__medium__straight_8py.html", "face__detection__test__medium__straight_8py" ],
    [ "face_detection_test_two_faces_jpg.py", "face__detection__test__two__faces__jpg_8py.html", "face__detection__test__two__faces__jpg_8py" ],
    [ "geolocation_pass_ipaddr.py", "geolocation__pass__ipaddr_8py.html", "geolocation__pass__ipaddr_8py" ],
    [ "human_detection_test.py", "human__detection__test_8py.html", "human__detection__test_8py" ],
    [ "news_explore_general.py", "news__explore__general_8py.html", "news__explore__general_8py" ],
    [ "ontology_is_subsuperclass_of_SpatialThing.py", "ontology__is__subsuperclass__of__SpatialThing_8py.html", "ontology__is__subsuperclass__of__SpatialThing_8py" ],
    [ "qr_detection_test_easy_far.py", "qr__detection__test__easy__far_8py.html", "qr__detection__test__easy__far_8py" ],
    [ "qr_detection_test_easy_medium.py", "qr__detection__test__easy__medium_8py.html", "qr__detection__test__easy__medium_8py" ],
    [ "qr_detection_test_easy_near.py", "qr__detection__test__easy__near_8py.html", "qr__detection__test__easy__near_8py" ],
    [ "qr_detection_test_hard_far.py", "qr__detection__test__hard__far_8py.html", "qr__detection__test__hard__far_8py" ],
    [ "qr_detection_test_hard_medium.py", "qr__detection__test__hard__medium_8py.html", "qr__detection__test__hard__medium_8py" ],
    [ "qr_detection_test_hard_near.py", "qr__detection__test__hard__near_8py.html", "qr__detection__test__hard__near_8py" ],
    [ "qr_detection_test_medium_far.py", "qr__detection__test__medium__far_8py.html", "qr__detection__test__medium__far_8py" ],
    [ "qr_detection_test_medium_medium.py", "qr__detection__test__medium__medium_8py.html", "qr__detection__test__medium__medium_8py" ],
    [ "qr_detection_test_medium_near.py", "qr__detection__test__medium__near_8py.html", "qr__detection__test__medium__near_8py" ],
    [ "speech_detection_google_test_ogg_sentence2.py", "speech__detection__google__test__ogg__sentence2_8py.html", "speech__detection__google__test__ogg__sentence2_8py" ],
    [ "speech_detection_sphinx_test_headset_deutera.py", "speech__detection__sphinx__test__headset__deutera_8py.html", "speech__detection__sphinx__test__headset__deutera_8py" ],
    [ "speech_detection_sphinx_test_headset_steile_mail.py", "speech__detection__sphinx__test__headset__steile__mail_8py.html", "speech__detection__sphinx__test__headset__steile__mail_8py" ],
    [ "speech_detection_sphinx_test_nao_wav_1_ch_email_robot.py", "speech__detection__sphinx__test__nao__wav__1__ch__email__robot_8py.html", "speech__detection__sphinx__test__nao__wav__1__ch__email__robot_8py" ],
    [ "speech_detection_sphinx_test_nao_wav_1_ch_thelw_voithia.py", "speech__detection__sphinx__test__nao__wav__1__ch__thelw__voithia_8py.html", "speech__detection__sphinx__test__nao__wav__1__ch__thelw__voithia_8py" ],
    [ "speech_detection_sphinx_test_ogg_deutera.py", "speech__detection__sphinx__test__ogg__deutera_8py.html", "speech__detection__sphinx__test__ogg__deutera_8py" ],
    [ "speech_detection_sphinx_test_ogg_monday.py", "speech__detection__sphinx__test__ogg__monday_8py.html", "speech__detection__sphinx__test__ogg__monday_8py" ],
    [ "speech_detection_sphinx_test_ogg_triti.py", "speech__detection__sphinx__test__ogg__triti_8py.html", "speech__detection__sphinx__test__ogg__triti_8py" ],
    [ "speech_detection_sphinx_test_ogg_tuesday.py", "speech__detection__sphinx__test__ogg__tuesday_8py.html", "speech__detection__sphinx__test__ogg__tuesday_8py" ],
    [ "speech_detection_sphinx_test_ogg_yes.py", "speech__detection__sphinx__test__ogg__yes_8py.html", "speech__detection__sphinx__test__ogg__yes_8py" ],
    [ "weather_report_current_Athens.py", "weather__report__current__Athens_8py.html", "weather__report__current__Athens_8py" ],
    [ "weather_report_forecast_Athens.py", "weather__report__forecast__Athens_8py.html", "weather__report__forecast__Athens_8py" ]
];