var namespacespeech__detection__sphinx__test__nao__wav__1__ch__nai__oxi =
[
    [ "RappInterfaceTest", "classspeech__detection__sphinx__test__nao__wav__1__ch__nai__oxi_1_1RappInterfaceTest.html", "classspeech__detection__sphinx__test__nao__wav__1__ch__nai__oxi_1_1RappInterfaceTest" ]
];