var namespacespeech__detection__sphinx__test__nao__wav__1__ch__thelw__voithia =
[
    [ "RappInterfaceTest", "classspeech__detection__sphinx__test__nao__wav__1__ch__thelw__voithia_1_1RappInterfaceTest.html", "classspeech__detection__sphinx__test__nao__wav__1__ch__thelw__voithia_1_1RappInterfaceTest" ]
];