var namespacespeech__detection__sphinx__test__nao__wav__1__ch__yes__no =
[
    [ "RappInterfaceTest", "classspeech__detection__sphinx__test__nao__wav__1__ch__yes__no_1_1RappInterfaceTest.html", "classspeech__detection__sphinx__test__nao__wav__1__ch__yes__no_1_1RappInterfaceTest" ]
];