std_msgs/String[] req_cols
rapp_platform_ros_communications/StringArrayMsg[] where_data
---
std_msgs/Bool success
std_msgs/String[] trace
std_msgs/String[] res_cols
rapp_platform_ros_communications/StringArrayMsg[] res_data
