string username
int64 fromTime
int64 toTime
---
rapp_platform_ros_communications/StringArrayMsg[] historyArithmeticCts
rapp_platform_ros_communications/StringArrayMsg[] historyReasoningCts
rapp_platform_ros_communications/StringArrayMsg[] historyRecallCts
bool success
string error
string[] trace

